### ISSUE TITLE
job-controller does not terminate after workflow finishes

### ISSUE THREAD

**Issue by mdonadoni** [reanahub/reana-workflow-engine-snakemake#50]
In some cases, the job-controller container inside a run-batch pod keeps running even though the workflow-engine container has already finished. The workflow is correctly reported as `failed`, but the run-batch pod continues running indefinitely.

How to reproduce:
1. Modify reana-demo-helloworld
    
    ```diff
    diff --git a/workflow/snakemake/Snakefile b/workflow/snakemake/Snakefile
    index e7344f2..e6f949b 100644
    --- a/workflow/snakemake/Snakefile
    +++ b/workflow/snakemake/Snakefile
    @@ -28,7 +28,4 @@ rule helloworld:
         container:
             "docker://python:2.7-slim"
         shell:
    -        "python {input.helloworld} "
    -        "--inputfile {input.inputfile} "
    -        "--outputfile {output} "
    -        "--sleeptime {params.sleeptime}"
    +        "echo"
    ```
2. Execute the workflow `reana-client run -f reana-snakemake.yaml`

**Comment by audrium** [comment]
It happens because we have `REANA_RUNTIME_KUBERNETES_KEEP_ALIVE_JOBS_WITH_STATUSES` set to `failed`  in [values-dev.yaml](https://github.com/reanahub/reana/blob/master/helm/configurations/values-dev.yaml#L12). Since Snakemake engine marks this workflow as failed it is kept for inspection [here](https://github.com/reanahub/reana-workflow-controller/blob/8858ad1cad2908036e0de55d24d98332ff7dc7cd/reana_workflow_controller/consumer.py#L163-L165). After removing that envar from the `values-dev.yaml` workflow run-batch pod is terminated as expected
